apiVersion: apps/v1
kind: Deployment
metadata:
  name: video processsing
  labels:
    app: video processsing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video processsing
  template:
    metadata:
      labels:
        app: video processsing
    spec:
      containers:
        - name: video processsing
          image: username/video processsing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5